// itens do cardápio
export const menu = [
  {
    id: 1,
    title: "Café Tradicional",
    category: "Bebidas",
    price: 3.00,
    img: "../assets/coffees/coffee.jpg",
    desc: `Nosso espresso tradicional, adoce como quiser - açúcar, adoçante ou mel - 200ml`,
    featured:false,
  },
  {
    id: 2,
    title: "Cappuccino Cremoso",
    category: "Bebidas",
    price: 6.00,
    img: "../assets/coffees/cappuccinoCremoso.jpg",
    desc: `Cappuccino tradicional com creme especial de chocolate e canela - 350ml`,
    featured:true,
  },
  {
    id: 3,
    title: "Cappuccino Coco Queimado",
    category: "Bebidas",
    price: 7.00,
    img: "../assets/coffees/coconutCoffee.jpg",
    desc: `Cappuccino de coco queimado com chantilly e lascas de coco - 300ml`,
    featured:false,
  },
  {
    id: 4,
    title: "Crispy Oreo",
    category: "Bebidas",
    price: 8.00,
    img: "../assets/coffees/oreoCoffee.jpeg",
    desc: `Cappuccino sabor baunilha com pedaços crocantes de Oreo e nosso creme especial de chocolate com canela. - 370ml`,
    featured:false,
  },
  {
    id: 5,
    title: "Cappuccino Marshmellow",
    category: "Bebidas",
    price: 8.00,
    img: "../assets/coffees/marshmellowCoffee.jpeg",
    desc: `Cappuccino de chocolate e avelã com marshmallows ao topo e borda de castanhas. - 300ml`,
    featured:false,
  },
  {
    id: 6,
    title: "Frappuccino Caramelo Salgado",
    category: "Bebidas",
    price: 8.00,
    img: "../assets/coffees/saltedCaramelCoffee.jpeg",
    desc: `Frappuccino sabor chocolate com chantilly e caramelo salgado - 370ml`,
    featured:false,
  },
  {
    id: 7,
    title: "Café Gelado",
    category: "Bebidas",
    price: 5.00,
    img: "../assets/coffees/iceCoffee.jpeg",
    desc: `Café gelado com leite e baunilha, adoce como quiser - açúcar, adoçante ou mel - 400ml`,
    featured:false,
  },
  {
    id: 8,
    title: "Café Gelado com Limão",
    category: "Bebidas",
    price: 6.00,
    img: "../assets/coffees/lemonCoffee.jpeg",
    desc: `Bebida gelada e gaseificada de limão com mel e espresso - 370ml`,
    featured:false,
  },
  {
    id: 9,
    title: "Croissant",
    category: "Lanches",
    price: 4.00,
    img: "../assets/snacks/croissant.jpg",
    desc: `Croissant salgado tradicional amanteigado (opcional: transforme seu croissant em uma versão doce com açúcar e canela)`,
    featured:false,
  },
  {
    id: 10,
    title: "Queijo Quente",
    category: "Lanches",
    price: 5.00,
    img: "../assets/snacks/cheeseBread.jpg",
    desc: `Tradicional pão na manteiga e queijo derretido`,
    featured:false,
  },
  {
    id: 11,
    title: "Torrada de Alho",
    category: "Lanches",
    price: 5.00,
    img: "../assets/snacks/alhoToast.jpg",
    desc: `Porção de pão de alho e ervas finas, servido com molho pesto`,
    featured:false,
  },
  {
    id: 12,
    title: "Tradicional Bacon Ovo",
    category: "Lanches",
    price: 6.00,
    img: "../assets/snacks/crispyBacon.jpg",
    desc: `Pão com manteiga servido com bacon e ovo frito`,
    featured:false,
  },
  {
    id: 13,
    title: "Croissant Caprese",
    category: "Lanches",
    price: 9.00,
    img: "../assets/snacks/caprese.jpg",
    desc: `Croissant recheado com tomate seco, queijo fresco e rúcula fresca.`,
    featured:true,
  },
  {
    id: 14,
    title: "Dadinhos de Tapioca",
    category: "Lanches",
    price: 10.00,
    img: "../assets/snacks/tapiocaDice.jpg",
    desc: `Dadinhos de tapioca fritos com geleia de pimenta agridoce`,
    featured:false,
  },
  {
    id: 15,
    title: "Wraps de Frango",
    category: "Lanches",
    price: 10.00,
    img: "../assets/snacks/miniWrap.jpg",
    desc: `Tortilhas de frango enroladas com catupiry`,
    featured:false,
  },
  {
    id: 16,
    title: "Chocowaffles",
    category: "Doces",
    price: 4.00,
    img: "../assets/desserts/waffle.jpg",
    desc: `Waffles de chocolate com morango e chantilly`,
    featured:false,
  },
  {
    id: 17,
    title: "Panquecas com Frutas Vermelhas",
    category: "Doces",
    price: 5.00,
    img: "../assets/desserts/pancake.jpg",
    desc: `Panqueca tradicional de baunilha com frutas vermelhas e mel`,
    featured:false,
  },
  {
    id: 18,
    title: "Pudim de Leite",
    category: "Doces",
    price: 6.00,
    img: "../assets/desserts/pudim.jpg",
    desc: `Pudim de leite com calda de caramelo`,
    featured:false,
  },
  {
    id: 19,
    title: "Red Velvet",
    category: "Doces",
    price: 7.00,
    img: "../assets/desserts/redVelvet.jpg",
    desc: `Fatia generosa do famoso Red Velvet.`,
    featured:true,
  },
  {
    id: 20,
    title: "Macarons de café",
    category: "Doces",
    price: 8.00,
    img: "../assets/desserts/macaron.jpg",
    desc: `Macarons de café recheados com creme de chocolate ao leite`,
    featured:false,
  },
  {
    id: 21,
    title: "Pistache Gâteau",
    category: "Doces",
    price: 10.00,
    img: "../assets/desserts/pistacheGâteau.jpg",
    desc: `Bolinhos de pistache com recheio de chocolate quente`,
    featured:false,
  },
];